// Keystone — the Codex's Concepts tab (P3-M8): short, textbook-neutral entries for the ecology terms the game uses,
// each with a plain-language definition and where it shows up in play. Standard terms only; no textbook or page cited,
// so the game fits any curriculum. `overlay` opens a map overlay from the entry; `see` lists related concepts.
window.Trophic = window.Trophic || {};

(function (T) {
  'use strict';

  T.CONCEPTS = [
    // ---------- energy ----------
    { id: 'gpp', topic: 'Energy', term: 'Gross primary production (GPP)',
      def: 'All the energy producers capture by photosynthesis in a given time. Much of it is used right away by the plants themselves.',
      where: 'The first step of the energy chain in the round report.', see: ['npp', 'plant-respiration'] },
    { id: 'plant-respiration', topic: 'Energy', term: 'Plant respiration',
      def: 'Energy producers spend staying alive: building, repairing and running their cells. It leaves as heat.',
      where: 'The loss between GPP and NPP in the energy chain.', see: ['gpp', 'npp'] },
    { id: 'npp', topic: 'Energy', term: 'Net primary production (NPP)',
      def: 'What’s left of GPP after plant respiration: new plant tissue, the food available to everything else. NPP efficiency is NPP ÷ GPP.',
      where: 'The energy chain and the bottom bar of the energy pyramid.', see: ['gpp', 'harvesting'] },
    { id: 'trophic-level', topic: 'Energy', term: 'Trophic level',
      def: 'A step in a food chain: producers, primary consumers (herbivores), secondary consumers (carnivores that eat herbivores) and so on. Omnivores feed at more than one level.',
      where: 'The pyramids in the left panel and the EHI’s energy component.', see: ['food-web', 'pyramid-energy'] },
    { id: 'food-web', topic: 'Energy', term: 'Food chain and food web',
      def: 'A food chain is one path energy takes from producer to top predator; a food web is all the chains in an ecosystem, linked.',
      where: 'The food web on the New world screen and each species’ diet in the Codex.', see: ['trophic-level'] },
    { id: 'harvesting', topic: 'Energy', term: 'Harvesting efficiency',
      def: 'The share of a level’s production that the level above actually eats. The rest dies uneaten and goes to decomposers.',
      where: 'Each “ingested” step of the energy chain. It’s different from the harvest limits the steward sets on game species.', see: ['assimilation', 'npp'] },
    { id: 'assimilation', topic: 'Energy', term: 'Assimilation efficiency',
      def: 'The share of food eaten that is digested and absorbed. The rest is egested as feces. Meat is easier to digest than plants, so carnivores assimilate more of what they eat.',
      where: 'The energy chain (GSP ÷ ingested) and the Consumer flow diagram.', see: ['gsp', 'tissue-growth'] },
    { id: 'gsp', topic: 'Energy', term: 'Gross and net secondary production (GSP, NSP)',
      def: 'For consumers, GSP is the energy assimilated; NSP is what’s left after respiration, the energy that becomes new tissue and offspring.',
      where: 'The energy chain’s “assimilated” and “tissue” steps.', see: ['assimilation', 'tissue-growth'] },
    { id: 'tissue-growth', topic: 'Energy', term: 'Tissue growth efficiency',
      def: 'NSP ÷ GSP: the share of assimilated energy that becomes new body tissue. Ectotherms keep far more than endotherms, which burn most of their energy keeping warm.',
      where: 'The energy chain and a species’ efficiencies in the inspector.', see: ['ectotherm', 'gsp'] },
    { id: 'ectotherm', topic: 'Energy', term: 'Ectotherm and endotherm',
      def: 'Ectotherms (insects, reptiles, amphibians, fish) take their body heat from the surroundings; endotherms (birds, mammals) make their own, at a large energy cost that rises in cold weather.',
      where: 'Tissue growth in the energy chain, split by ectotherms and endotherms.', see: ['tissue-growth'] },
    { id: 'ten-percent', topic: 'Energy', term: 'Energy transfer between levels',
      def: 'Only a small share of the energy at one trophic level reaches the next, often around 10% and sometimes far less. That is why food chains are short and top predators are rare.',
      where: 'The share passed up beside each bar of the energy pyramid, and the EHI’s energy component.', see: ['pyramid-energy', 'realism'] },
    { id: 'pyramid-numbers', topic: 'Energy', term: 'Pyramid of numbers',
      def: 'How many individuals are at each trophic level. It can be inverted: one tree can feed thousands of insects.',
      where: 'Numbers tab of the pyramid in the left panel.', see: ['pyramid-biomass', 'pyramid-energy'] },
    { id: 'pyramid-biomass', topic: 'Energy', term: 'Pyramid of biomass',
      def: 'The mass of living tissue at each level at one moment. It can be inverted when producers grow and are eaten fast, like plankton.',
      where: 'Biomass tab of the pyramid (grams per square metre).', see: ['pyramid-numbers', 'pyramid-energy'] },
    { id: 'pyramid-energy', topic: 'Energy', term: 'Pyramid of energy',
      def: 'The energy fixed at each level over a period. It always narrows going up, because energy is lost as heat at every step.',
      where: 'Energy tab of the pyramid; the game checks every round that it narrows.', see: ['ten-percent'] },
    { id: 'realism', topic: 'Energy', term: 'Game and Realism modes',
      def: 'Game mode raises some efficiencies (endotherm tissue growth, sunlight captured) so the map can hold its predators. Realism mode uses the textbook’s ranges throughout.',
      where: 'The Realism option on the New world screen; the report shows the target band for the mode you’re in.', see: ['ten-percent'] },

    // ---------- populations ----------
    { id: 'population-change', topic: 'Populations', term: 'Population change: N₁ = N₀ + B + I − D − E',
      def: 'A population next year is this year’s, plus births and immigrants, minus deaths and emigrants. The growth rate r compares the gains and losses with N₀.',
      where: 'The Demography table in the round report.', see: ['carrying-capacity', 'growth-curves'] },
    { id: 'carrying-capacity', topic: 'Populations', term: 'Carrying capacity (K)',
      def: 'The largest population an area can support over time, set by food, space, water and other limits.',
      where: 'K in the Demography table and the harvest table (for studied species). A harvest is most sustainable near ½K.', see: ['growth-curves', 'mvp'] },
    { id: 'growth-curves', topic: 'Populations', term: 'Exponential and logistic growth',
      def: 'With plenty of resources a population grows exponentially (a J curve); as it nears K growth slows (an S curve). Overshoot is a rise past K followed by a crash.',
      where: 'The Curve column of the Demography table.', see: ['carrying-capacity'] },
    { id: 'mvp', topic: 'Populations', term: 'Minimum viable population',
      def: 'The smallest population likely to survive bad years, disease and chance. Below it, a population can slide toward extinction.',
      where: 'The EHI’s viability component; translocation bolsters small populations.', see: ['allee'] },
    { id: 'allee', topic: 'Populations', term: 'Allee effect',
      def: 'In some species, individuals do worse when there are too few of them, for example when mates are hard to find.',
      where: 'Species that breed in explosive groups need enough adults nearby.', see: ['mvp'] },
    { id: 'territory', topic: 'Populations', term: 'Territoriality',
      def: 'Animals that defend an area keep others out of it. Floaters without a territory often can’t breed, which caps the population.',
      where: 'The Territories map overlay.', overlay: 'territories', see: ['carrying-capacity'] },
    { id: 'estimate', topic: 'Populations', term: 'Population estimates and detection',
      def: 'Managers rarely count every animal. Surveys catch or see a share of the individuals in an area and scale up, giving an estimate with an error margin that grows as data get older.',
      where: 'Survey actions in the Monitor bar, estimates ± error in the harvest table, and the Survey coverage overlay.', overlay: 'survey', see: ['mark-recapture'] },
    { id: 'mark-recapture', topic: 'Populations', term: 'Mark and recapture',
      def: 'Catch, mark and release animals, then catch again: the share of marked animals in the second catch estimates the whole population.',
      where: 'Live traps and mist nets.', see: ['estimate'] },

    // ---------- interactions ----------
    { id: 'keystone', topic: 'Interactions', term: 'Keystone species',
      def: 'A species whose effect on its community is far larger than its numbers suggest. Removing it changes the whole community.',
      where: 'Keystone tests in the round report, which replay the world without each candidate, and ★ in the Codex.', see: ['trophic-cascade'] },
    { id: 'trophic-cascade', topic: 'Interactions', term: 'Trophic cascade',
      def: 'When a predator’s effect ripples down a food chain: fewer herbivores, so more plants.',
      where: 'Reintroducing an apex predator, and the populations chart afterwards.', see: ['keystone'] },
    { id: 'mutualism', topic: 'Interactions', term: 'Mutualism',
      def: 'An interaction that benefits both species (+/+), like pollinators and the flowers they feed on.',
      where: 'The Interactions card in the round report.', see: ['commensalism', 'parasitism'] },
    { id: 'commensalism', topic: 'Interactions', term: 'Commensalism',
      def: 'One species benefits and the other is unaffected (+/0), like scavengers following a predator to its kills.',
      where: 'The Interactions card.', see: ['mutualism', 'amensalism'] },
    { id: 'amensalism', topic: 'Interactions', term: 'Amensalism',
      def: 'One species is harmed and the other is unaffected (0/−), like small animals’ burrows trampled by large grazers.',
      where: 'The Interactions card.', see: ['commensalism'] },
    { id: 'parasitism', topic: 'Interactions', term: 'Parasitism',
      def: 'One species benefits at the other’s expense (+/−), usually without killing it quickly. Nest parasites lay eggs in other birds’ nests.',
      where: 'The Interactions card.', see: ['mutualism'] },
    { id: 'competition', topic: 'Interactions', term: 'Competition and competitive exclusion',
      def: 'Species that need the same limited resource compete (−/−). Two species can’t share exactly the same niche for long: one wins out.',
      where: 'Warnings in the Interactions card when two species overlap heavily.', see: ['strata'] },
    { id: 'strata', topic: 'Interactions', term: 'Stratification',
      def: 'Vegetation in layers (ground, herbs, shrubs, canopy) gives animals different places to feed, so more species can share an area.',
      where: 'The Vegetation layers map overlay, and each species’ foraging layer in the Codex.', overlay: 'stratum', see: ['competition'] },
    { id: 'diversity', topic: 'Interactions', term: 'Species richness and diversity',
      def: 'Richness is how many species there are. A diversity index such as Shannon’s H also weighs how evenly individuals are spread among them.',
      where: 'The Interactions card header and the EHI’s biodiversity component.', see: [] },

    // ---------- succession and habitat ----------
    { id: 'succession', topic: 'Succession and habitat', term: 'Ecological succession',
      def: 'The gradual change in a community after a disturbance: bare ground to pioneers, grasses, shrubs and, where the climate allows, forest. Primary succession starts on bare rock; secondary succession starts where soil remains.',
      where: 'The Seral stage map overlay and the succession strip in the left panel.', overlay: 'seral', see: ['climax', 'disturbance'] },
    { id: 'climax', topic: 'Succession and habitat', term: 'Climax community',
      def: 'The stable community succession tends toward in a given climate: prairie in dry grassland climates, forest in wetter ones.',
      where: 'Climax in the succession strip; the Whittaker diagram on the New world screen.', see: ['succession', 'biome'] },
    { id: 'disturbance', topic: 'Succession and habitat', term: 'Disturbance',
      def: 'An event such as fire, flood, windthrow or grazing that removes part of a community and restarts succession on that patch.',
      where: 'Prescribed burns, discing and natural events.', see: ['succession'] },
    { id: 'biome', topic: 'Succession and habitat', term: 'Biome and climate',
      def: 'Temperature and rainfall together decide the kind of community a region can hold: tundra, taiga, grassland, desert, temperate forest or rainforest.',
      where: 'The Whittaker diagram on the New world screen.', see: ['climax'] },
    { id: 'edge', topic: 'Succession and habitat', term: 'Edge effects and interior habitat',
      def: 'Where woodland meets open ground, conditions change: more light, more predators and nest parasites. Some species need interior habitat far from any edge.',
      where: 'The Edge vs interior map overlay and the EHI’s habitat component.', overlay: 'edge', see: ['fragmentation'] },
    { id: 'fragmentation', topic: 'Succession and habitat', term: 'Habitat fragmentation',
      def: 'Breaking habitat into small, separate pieces. Small patches are mostly edge, and populations in them are cut off from each other.',
      where: 'Wildlife corridors link fragments.', see: ['edge'] },
    { id: 'invasive', topic: 'Succession and habitat', term: 'Invasive species',
      def: 'A non-native species that spreads and harms the community it enters, often because its natural enemies aren’t there.',
      where: 'Invasive control in the Wildlife actions.', see: [] },

    // ---------- cycles ----------
    { id: 'nitrogen-fixation', topic: 'Nutrient, water and carbon cycles', term: 'Nitrogen fixation',
      def: 'Turning nitrogen gas from the air into a form living things can use. Bacteria in legume root nodules and some free-living soil microbes do it.',
      where: 'Plant legumes action; fixation in the left panel’s soil nitrogen figures.', overlay: 'nitrogen', see: ['nitrification'] },
    { id: 'nitrification', topic: 'Nutrient, water and carbon cycles', term: 'Nitrification and denitrification',
      def: 'Soil bacteria turn ammonium into nitrate (nitrification). In waterlogged or compacted soil, others turn nitrate back into nitrogen gas that escapes to the air (denitrification).',
      where: 'Soil nitrogen in the left panel (needs a soil test) and the Soil nitrogen overlay.', overlay: 'nitrogen', see: ['leaching'] },
    { id: 'leaching', topic: 'Nutrient, water and carbon cycles', term: 'Leaching and runoff',
      def: 'Water draining through or across soil carries dissolved nitrate away into groundwater and streams.',
      where: 'Riparian buffers catch runoff; the Dry plains aquifer goal.', see: ['nitrification', 'water-table'] },
    { id: 'water-table', topic: 'Nutrient, water and carbon cycles', term: 'Groundwater and the water table',
      def: 'Water that soaks deep into the ground fills an aquifer; the top of that saturated zone is the water table. Pumping faster than rain recharges it lowers the table.',
      where: 'The Well gauge action and the Soil water overlay.', overlay: 'moisture', see: ['leaching'] },
    { id: 'carbon-sink', topic: 'Nutrient, water and carbon cycles', term: 'Carbon sinks and sources',
      def: 'An ecosystem is a carbon sink when it stores more carbon (in wood, soil and peat) than it releases. Burning, clearing and soil loss turn it into a source.',
      where: 'The Soil carbon overlay and the carbon figures in the left panel.', overlay: 'carbon', see: [] },

    // ---------- management ----------
    { id: 'sustainable-yield', topic: 'Management', term: 'Sustainable yield',
      def: 'A harvest a population can replace every year. It’s greatest when the population is held around half its carrying capacity, where it grows fastest.',
      where: 'Harvest limits in the Plan panel; the Harvest pressure overlay.', overlay: 'harvest', see: ['carrying-capacity'] },
    { id: 'reintroduction', topic: 'Management', term: 'Reintroduction and translocation',
      def: 'Returning a species to where it has died out, or moving individuals to bolster a small population.',
      where: 'The Wildlife actions.', see: ['mvp', 'trophic-cascade'] },
    { id: 'stakeholders', topic: 'Management', term: 'Stakeholders and ecosystem services',
      def: 'People who depend on or care about an ecosystem: ranchers, farmers, hunters, towns, conservation groups. Ecosystem services are the benefits they draw from it, such as forage, clean water and timber.',
      where: 'The community in the Plan panel and its asks each round.', overlay: 'land', see: [] },
  ];
  T.conceptById = id => T.CONCEPTS.find(c => c.id === id) || null;
})(window.Trophic);
