// Generated by tools/catalog/build.js — the ecoregion catalogs that have been built.
window.Trophic = window.Trophic || {};
Trophic.CATALOG_INDEX = [{"code":"5.2","name":"Mixed Wood Shield","level":2,"species":311,"biome":"taiga","tMean":4.9,"rain":78,"built":"2026-09-23"},{"code":"9.3","name":"West-Central Semi-Arid Prairies","level":2,"species":311,"biome":"temperate grassland","tMean":6.2,"rain":58,"built":"2026-09-23"},{"code":"9.4.6","name":"Edwards Plateau","level":3,"species":499,"biome":"temperate grassland","tMean":20.3,"rain":67,"built":"2026-09-23"}];
